version: '3.8'

volumes:
  mongodbdata:

networks:
  backend_net:
    driver: bridge

services:
  api:
    image: patrickdevv/rotten-potatoes:v1
    ports:
      - 5000:5000
    networks:
      - backend_net
    depends_on:
      - mongodb
    environment:
      MONGODB_DB: admin
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_USERNAME: mongouser
      MONGODB_PASSWORD: mongopwd

  mongodb:
    image: mongo:4.4.3
    container_name: mongodb_rotten
    ports:
      - 27017:27017
    networks:
      - backend_net
    volumes:
      - mongodbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
      MONGO_INITDB_ROOT_DATABASE: admin